In [5]:
import pandas as pd

In [6]:
from datasets import load_dataset

dataset = load_dataset("conll2003")

Found cached dataset conll2003 (/home/trivikram/.cache/huggingface/datasets/conll2003/conll2003/1.0.0/9a4d16a94f8674ba3466315300359b0acd891b68b6c8743ddf60b9c702adce98)

  0%|          | 0/3 [00:00<?, ?it/s]

In [7]:
dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 14041
    })
    validation: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3250
    })
    test: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3453
    })
})

In [8]:
train_data = dataset["train"]
train_df = pd.DataFrame(train_data)
validation_data=dataset["validation"]
validation_df=pd.DataFrame(validation_data)
test_data=dataset["test"]
test_df=pd.DataFrame(test_data)

In [9]:
len(train_df.iloc[0]['chunk_tags'])

9

In [31]:
pos=[]
chunks=[]
ner=[]
tokens=[]
firsts=[]
for i in range(train_df.shape[0]):
    pos.extend(train_df.iloc[i]["pos_tags"])
    tokens.extend(train_df.iloc[i]["tokens"])
    chunks.extend(train_df.iloc[i]["chunk_tags"])
    ner.extend(train_df.iloc[i]["ner_tags"])
X_train=pd.DataFrame(columns=['POS','Chunks'])
y_train=pd.DataFrame(columns=['NER'])

X_train['POS']=pos
X_train['Chunks']=chunks

digits=[]
case=[]
title=[]
for i in tokens:
    if i.isdigit()==True:
            digits.append(1)
            case.append(0)
            title.append(0)
    else:
        digits.append(0)
        if i[0].isupper():
            case.append(1)
        else:
            case.append(0)
        if i.istitle():
            title.append(1)
        else:
            title.append(0)

X_train['Case']=case
X_train['Digits']=digits
X_train['Title']=title

mod=[]
for i in ner:
    if i==0:
        mod.append(0)
    else:
        mod.append(1)
y_train['NER']=mod

In [26]:
pos=[]
chunks=[]
ner=[]
tokens=[]
for i in range(validation_df.shape[0]):
    tokens.extend(validation_df.iloc[i]["tokens"])
    pos.extend(validation_df.iloc[i]["pos_tags"])
    chunks.extend(validation_df.iloc[i]["chunk_tags"])
    ner.extend(validation_df.iloc[i]["ner_tags"])

X_val=pd.DataFrame(columns=['POS','Chunks'])
y_val=pd.DataFrame(columns=['NER'])

X_val['POS']=pos
X_val['Chunks']=chunks



digits=[]
case=[]
title=[]
for i in tokens:
    if i.isdigit()==True:
            digits.append(1)
            case.append(0)
            title.append(0)
    else:
        digits.append(0)
        if i[0].isupper():
            case.append(1)
        else:
            case.append(0)
        if i.istitle():
            title.append(1)
        else:
            title.append(0)

X_val['Case']=case
X_val['Digits']=digits
X_val['Title']=title



mod=[]
for i in ner:
    if i==0:
        mod.append(0)
    else:
        mod.append(1)
y_val['NER']=mod

In [16]:
len(tokens)

51362

In [27]:
pos=[]
chunks=[]
ner=[]
tokens=[]

for i in range(test_df.shape[0]):
    tokens.extend(test_df.iloc[i]["tokens"])
    pos.extend(test_df.iloc[i]["pos_tags"])
    chunks.extend(test_df.iloc[i]["chunk_tags"])
    ner.extend(test_df.iloc[i]["ner_tags"])

X_test=pd.DataFrame(columns=['POS','Chunks'])
y_test=pd.DataFrame(columns=['NER'])

X_test['POS']=pos
X_test['Chunks']=chunks



digits=[]
case=[]
title=[]
for i in tokens:
    if i.isdigit()==True:
            digits.append(1)
            case.append(0)
            title.append(0)
    else:
        digits.append(0)
        if i[0].isupper():
            case.append(1)
        else:
            case.append(0)
        if i.istitle():
            title.append(1)
        else:
            title.append(0)

X_test['Case']=case
X_test['Digits']=digits
X_test['Title']=title

mod=[]
for i in ner:
    if i==0:
        mod.append(0)
    else:
        mod.append(1)
y_test['NER']=mod

In [33]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB(alpha=0.01)
nb.fit(X_train, y_train)
nb.score(X_val,y_val)

/home/trivikram/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9328102488220864

In [34]:
nb.score(X_test,y_test)

0.9247334984386777

In [35]:
# Train an SVM classifier
from sklearn.svm import SVC
svm_classifier = SVC(kernel="rbf")
svm_classifier.fit(X_train, y_train)

# Predict on the test data
predictions = svm_classifier.predict(X_val)

/home/trivikram/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

MAIN CLASSIFIER BELOW

In [37]:
svm_classifier.score(X_test,y_test)

0.947302681167223

In [24]:
ner

[0,
 0,
 5,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 5,
 0,
 5,
 6,
 6,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 7,
 8,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 0,
 0,
 0,
 7,
 8,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 8,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 7,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 7,
 8,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 5,
 0,
 5,
 6,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 4,
 0,
 1,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 5,
 0,
 5,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 5,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 7,
 8,
 8,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 8,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 5,
 0,
 5,
 0,
 5,
 6,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 7,
 8,
 0,
 0,
 5,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 ...]

In [22]:
import numpy as np
y = np.bincount(predictions)
ii = np.nonzero(y)[0]
np.vstack((ii,y[ii])).T

array([[    0, 51362]])

In [40]:
import os
scores=''
if os.path.getsize("model.pkl") > 0:      
    with open(target, "rb") as f:
        unpickler = pickle.Unpickler(f)
        print("unpickler")
        # if file is not empty scores will be equal
        # to the value unpickled
        scores = unpickler.load()

In [41]:
loaded_model = pickle.load(open("model.pkl", 'rb'))

EOFError: Ran out of input

In [42]:
model_pkl_file = "svm_classifier_model.pkl"
with open(model_pkl_file, 'rb') as file:  
    model = pickle.load(file)

# evaluate model

/home/trivikram/anaconda3/lib/python3.11/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator SVC from version 1.2.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [44]:
model.score(X_test,y_test)

0.8253041886508022

In [ ]:
mlb = MultiLabelBinarizer()
labels = mlb.fit_transform(train_df["ner_tags"])
print(classification_report(y_val, predictions, target_names=mlb.classes_))

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.svm import SVC
from sklearn.metrics import classification_report
import numpy as np

data=train_df

# Convert tokens, pos_tags, and chunk_tags to strings
tokens_str = [" ".join(sentence) for sentence in data["tokens"]]
pos_tags_str = [" ".join(map(str, tags)) for tags in data["pos_tags"]]
chunk_tags_str = [" ".join(map(str, tags)) for tags in data["chunk_tags"]]

# Combine features into a feature matrix
features = [f"{tokens} {pos_tags} {chunk_tags}" for tokens, pos_tags, chunk_tags in zip(tokens_str, pos_tags_str, chunk_tags_str)]

# Convert NER tags to numerical labels
mlb = MultiLabelBinarizer()
labels = mlb.fit_transform(data["ner_tags"])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

# Vectorize the text data
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)


y_train_flat = np.ravel(y_train)
y_test_flat = np.ravel(y_test)

# Train an SVM classifier
svm_classifier = SVC(kernel="linear")
svm_classifier.fit(X_train, y_train)

# Predict on the test data
predictions = svm_classifier.predict(X_test_vec)

# Convert numerical predictions back to NER tags
predicted_labels = mlb.inverse_transform(predictions)

# Print classification report
print(classification_report(y_test_flat, predictions, target_names=mlb.classes_))

ValueError: could not convert string to float: 'Baseball games played on Friday ( home team in CAPS ) : 21 24 40 15 22 4 21 21 15 22 5 8 11 12 21 13 11 0 11 12 13 11 0 0'

In [25]:
print("X_train_vec shape:", X_train_vec.shape)
print("X_test_vec shape:", X_test_vec.shape)
print("y_train_flat shape:", y_train.shape)
print("y_test_flat shape:", y_test.shape)

X_train_vec shape: (11232, 16008)
X_test_vec shape: (2809, 16008)
y_train_flat shape: (11232, 9)
y_test_flat shape: (2809, 9)

In [11]:
features

['EU rejects German call to boycott British lamb . 22 42 16 21 35 37 16 21 7 11 21 11 12 21 22 11 12 0',
 'Peter Blackburn 22 22 11 12',
 'BRUSSELS 1996-08-22 22 11 11 12',
 'The European Commission said on Thursday it disagreed with German advice to consumers to shun British lamb until scientists determine whether mad cow disease can be transmitted to sheep . 12 22 22 38 15 22 28 38 15 16 21 35 24 35 37 16 21 15 24 41 15 16 21 21 20 37 40 35 21 7 11 12 12 21 13 11 11 21 13 11 12 13 11 21 22 11 12 17 11 21 17 11 12 12 21 22 22 13 11 0',
 "Germany 's representative to the European Union 's veterinary committee Werner Zwingmann said on Wednesday consumers should buy sheepmeat from countries other than Britain until the scientific advice was clearer . 22 27 21 35 12 22 22 27 16 21 22 22 38 15 22 24 20 37 21 15 24 16 15 22 15 12 16 21 38 17 7 11 11 12 13 11 12 12 11 12 12 12 12 21 13 11 12 21 22 11 13 11 1 13 11 17 11 12 12 21 1 0",
 '" We do n\'t support any such recommendation because we do n\'t see any grounds for it , " the Commission \'s chief spokesman Nikolaus van der Pas told a news briefing . 0 28 41 30 37 12 16 21 15 28 41 30 37 12 24 15 28 6 0 12 22 27 16 21 22 22 14 22 38 12 21 21 7 0 11 21 22 22 11 12 12 17 11 21 22 22 11 12 13 11 0 0 11 12 11 12 12 12 12 12 12 21 11 12 12 0',
 'He said further scientific study was required and if it was found that action was needed it should be taken by the European Union . 28 38 16 16 21 38 40 10 15 28 38 40 15 21 38 40 28 20 37 40 15 12 22 22 7 11 21 11 12 12 21 22 0 17 11 21 22 17 11 21 22 11 21 22 22 13 11 12 12 0',
 'He said a proposal last month by EU Farm Commissioner Franz Fischler to ban sheep brains , spleens and spinal cords from the human and animal food chains was a highly specific and precautionary move to protect human health . 28 38 12 21 16 21 15 22 22 22 22 22 35 37 21 24 6 24 10 16 24 15 12 21 10 21 21 24 38 12 30 16 10 16 21 35 37 16 21 7 11 21 11 12 11 12 13 11 12 12 12 12 21 22 11 12 0 11 0 11 12 13 11 12 12 12 12 12 21 11 12 1 2 2 11 21 22 11 12 0',
 'Fischler proposed EU-wide measures after reports from Britain and France that under laboratory conditions sheep could contract Bovine Spongiform Encephalopathy ( BSE ) -- mad cow disease . 17 40 22 42 15 24 15 22 10 22 43 15 21 24 21 20 37 22 22 22 4 22 5 8 16 21 21 7 11 12 12 21 13 11 13 11 12 12 11 13 11 11 12 21 22 11 12 12 0 11 0 0 11 12 12 0',
 "But Fischler agreed to review his proposal after the EU 's standing veterinary committee , mational animal health officials , questioned if such action was justified as there was only a slight risk to human health . 10 22 38 35 37 29 21 15 12 22 27 21 16 21 6 16 21 21 24 6 38 15 16 21 38 40 15 30 38 30 12 16 21 35 16 21 7 0 11 21 22 22 11 12 13 11 12 11 12 12 12 0 11 12 12 12 0 21 17 11 12 21 22 13 3 21 3 11 12 12 13 11 12 0",
 'Spanish Farm Minister Loyola de Palacio had earlier accused Fischler at an EU farm ministers \' meeting of causing unjustified alarm through " dangerous generalisation . " 22 22 22 22 22 22 38 31 40 22 15 12 16 21 24 27 21 15 39 16 21 15 0 16 21 7 0 11 12 12 12 12 12 21 22 22 11 13 11 12 12 12 11 12 13 21 1 11 13 0 11 12 0 0',
 '. 7 0',
 "Only France and Britain backed Fischler 's proposal . 30 22 10 22 38 22 27 21 7 11 12 12 12 21 11 11 12 0",
 "The EU 's scientific veterinary and multidisciplinary committees are due to re-examine the issue early next month and make recommendations to the senior veterinary officials . 12 22 27 16 16 10 16 24 41 16 35 37 12 21 30 16 21 10 37 24 35 12 16 16 24 7 11 12 11 12 12 12 12 12 21 1 21 22 11 12 11 12 12 0 21 11 13 11 12 12 12 0",
 'Sheep have long been known to contract scrapie , a brain-wasting disease similar to BSE which is believed to have been transferred to cattle through feed containing animal waste . 22 41 30 40 40 35 21 21 6 12 16 21 16 35 22 43 42 40 35 37 40 40 35 24 15 21 39 21 21 7 11 21 22 22 22 13 11 12 0 11 12 12 1 13 11 11 21 22 22 22 22 22 13 11 13 11 21 11 12 0',
 'British farmers denied on Thursday there was any danger to human health from their sheep , but expressed concern that German government advice to consumers to avoid British lamb might influence consumers across Europe . 16 24 40 15 22 13 38 12 21 35 16 21 15 29 21 6 10 38 21 15 16 21 21 35 24 35 37 16 21 20 37 24 15 22 7 11 12 21 13 11 11 21 11 12 13 11 12 13 11 12 0 0 21 11 17 11 12 12 13 11 21 22 11 12 21 22 11 13 11 0',
 '" What we have to be extremely careful of is how other countries are going to take Germany \'s lead , " Welsh National Farmers \' Union ( NFU ) chairman John Lloyd Jones said on BBC radio . 0 44 28 41 35 37 30 16 15 42 46 16 24 41 39 35 37 22 27 21 6 0 22 22 22 27 22 4 22 5 21 22 22 22 38 15 22 21 7 0 11 11 21 22 22 1 2 13 21 3 11 12 21 22 22 22 11 11 12 0 0 11 12 12 11 12 0 11 0 11 12 12 12 21 13 11 12 0',
 'Bonn has led efforts to protect public health after consumer confidence collapsed in March after a British report suggested humans could contract an illness similar to mad cow disease by eating contaminated beef . 22 42 40 24 35 37 16 21 15 21 21 38 15 22 15 12 16 21 38 24 20 37 12 21 16 35 16 21 21 15 39 40 21 7 11 21 22 11 21 22 11 12 13 11 12 21 13 11 13 11 12 12 21 11 21 22 11 12 1 2 2 11 12 13 21 22 11 0',
 'Germany imported 47,600 sheep from Britain last year , nearly half of total imports . 22 38 11 21 15 22 16 21 6 30 21 15 16 24 7 11 21 11 12 13 11 11 12 0 11 12 13 11 12 0',
 'It brought in 4,275 tonnes of British mutton , some 10 percent of overall imports . 28 38 15 11 24 15 16 21 6 12 11 21 15 16 24 7 11 21 13 11 12 13 11 12 0 11 12 12 13 11 12 0',
 'Rare Hendrix song draft sells for almost $ 17,000 . 22 22 21 21 42 15 30 3 11 7 11 12 12 12 21 13 11 12 12 0',
 'LONDON 1996-08-22 22 11 11 12',
 "A rare early handwritten draft of a song by U.S. guitar legend Jimi Hendrix was sold for almost $ 17,000 on Thursday at an auction of some of the late musician 's favourite possessions . 12 16 16 16 21 15 12 21 15 22 21 21 22 22 38 40 15 30 3 11 15 22 15 12 21 15 12 15 12 16 21 27 16 24 7 11 12 12 12 12 13 11 12 13 11 12 12 12 12 21 22 13 11 12 12 13 11 13 11 12 13 11 13 11 12 12 11 12 12 0",
 'A Florida restaurant paid 10,925 pounds ( $ 16,935 ) for the draft of " Ai n\'t no telling " , which Hendrix penned on a piece of London hotel stationery in late 1966 . 12 22 21 38 11 24 4 3 11 5 15 12 21 15 0 42 30 12 39 0 6 43 22 40 15 12 21 15 22 21 21 15 16 11 7 11 12 12 21 11 12 0 11 12 0 13 11 12 13 0 21 0 11 21 0 0 11 11 21 13 11 12 13 11 12 12 13 11 12 0',
 'At the end of a January 1967 concert in the English city of Nottingham he threw the sheet of paper into the audience , where it was retrieved by a fan . 15 12 21 15 12 22 11 21 15 12 16 21 15 22 28 38 12 21 15 21 15 12 21 6 46 28 38 40 15 12 21 7 13 11 12 13 11 12 12 12 13 11 12 12 13 11 11 21 11 12 13 11 13 11 12 0 3 11 21 22 13 11 12 0',
 "Buyers also snapped up 16 other items that were put up for auction by Hendrix 's former girlfriend Kathy Etchingham , who lived with him from 1966 to 1969 . 24 30 38 30 11 16 24 43 38 40 33 15 21 15 22 27 16 21 22 22 6 44 38 15 28 15 11 35 11 7 11 3 21 3 11 12 12 11 21 22 15 13 11 13 11 11 12 12 12 12 0 11 21 13 11 13 11 13 11 0",
 'They included a black lacquer and mother of pearl inlaid box used by Hendrix to store his drugs , which an anonymous Australian purchaser bought for 5,060 pounds ( $ 7,845 ) . 28 38 12 16 21 10 21 15 21 38 21 40 15 22 35 37 29 24 6 43 12 16 16 21 38 15 11 24 4 3 11 5 7 11 21 11 12 12 12 12 13 11 21 11 21 13 11 21 22 11 12 0 11 11 12 12 12 21 13 11 12 0 11 12 0 0',
 'The guitarist died of a drugs overdose in 1970 aged 27 . 12 21 38 15 12 24 21 15 11 40 11 7 11 12 21 13 11 12 12 13 11 1 11 0',
 'China says Taiwan spoils atmosphere for talks . 22 42 22 42 21 15 24 7 11 21 11 21 11 13 11 0',
 'BEIJING 1996-08-22 39 11 21 11',
 'China on Thursday accused Taipei of spoiling the atmosphere for a resumption of talks across the Taiwan Strait with a visit to Ukraine by Taiwanese Vice President Lien Chan this week that infuriated Beijing . 22 15 22 38 22 15 39 12 21 15 12 21 15 24 15 12 22 22 15 12 21 35 22 15 22 22 22 22 22 12 21 43 38 22 7 11 13 11 21 11 13 21 11 12 13 11 12 13 11 13 11 12 12 13 11 12 13 11 13 11 12 12 12 12 11 12 11 21 11 0',
 'Speaking only hours after Chinese state media said the time was right to engage in political talks with Taiwan , Foreign Ministry spokesman Shen Guofang told Reuters : " The necessary atmosphere for the opening of the talks has been disrupted by the Taiwan authorities . " 39 16 24 15 16 21 24 38 12 21 38 30 35 37 15 16 24 15 22 6 22 22 21 22 22 38 22 8 0 12 16 21 15 12 21 15 12 24 42 40 40 15 12 22 24 7 0 21 3 11 13 11 12 12 21 11 12 21 1 21 22 13 11 12 13 11 0 11 12 12 12 12 21 11 0 0 11 12 12 13 11 12 13 11 12 21 22 22 13 11 12 12 0 0',
 "State media quoted China 's top negotiator with Taipei , Tang Shubei , as telling a visiting group from Taiwan on Wednesday that it was time for the rivals to hold political talks . 21 24 38 22 27 16 21 15 22 6 22 22 6 15 39 12 16 21 15 22 15 22 15 28 38 21 15 12 24 35 37 16 24 7 11 12 21 11 11 12 12 13 11 0 11 12 0 13 21 11 12 12 13 11 13 11 17 11 21 11 13 11 12 21 22 11 12 0",
 '" Now is the time for the two sides to engage in political talks ... 0 30 42 12 21 15 12 11 24 35 37 15 16 24 8 0 3 21 11 12 13 11 12 12 21 22 13 11 12 0',
 'that is to end the state of hostility , " Thursday \'s overseas edition of the People \'s Daily quoted Tang as saying . 43 42 35 37 12 21 15 21 6 0 22 27 16 21 15 12 23 27 16 40 22 15 39 7 11 21 21 22 11 12 13 11 0 0 11 11 12 12 13 11 12 11 12 21 11 13 21 0',
 "The foreign ministry 's Shen told Reuters Television in an interview he had read reports of Tang 's comments but gave no details of why the negotiator had considered the time right for talks with Taiwan , which Beijing considers a renegade province . 12 16 21 27 22 38 22 22 15 12 21 28 38 40 24 15 22 27 24 10 38 12 24 15 46 12 21 38 40 12 21 30 15 24 15 22 6 43 22 42 12 21 21 7 11 12 12 11 12 21 11 12 13 11 12 11 21 22 11 13 11 11 12 0 21 11 12 13 3 11 12 21 22 11 12 3 13 11 13 11 0 11 11 21 11 12 12 0",
 'China , which has long opposed all Taipei efforts to gain greater international recognition , was infuriated by a visit to Ukraine this week by Taiwanese Vice President Lien . 22 6 43 42 30 40 12 22 24 35 37 17 16 21 6 38 40 15 12 21 35 22 12 21 15 22 22 22 22 7 11 0 11 21 22 22 11 12 12 21 22 11 12 12 0 21 22 13 11 12 13 11 11 12 13 11 12 12 12 0',
 'China says time right for Taiwan talks . 22 42 21 30 15 22 24 7 11 21 11 3 13 11 12 0',
 'BEIJING 1996-08-22 39 11 21 11',
 'China has said it was time for political talks with Taiwan and that the rival island should take practical steps towards that goal . 22 42 38 28 38 21 15 16 24 15 22 10 15 12 16 21 20 37 16 24 15 12 21 7 11 21 22 11 21 11 13 11 12 13 11 0 17 11 12 12 21 22 11 12 13 11 12 0',
 'Consultations should be held to set the time and format of the talks , the official Xinhua news agency quoted Tang Shubei , executive vice chairman of the Association for Relations Across the Taiwan Straits , as saying late on Wednesday . 24 20 37 40 35 37 12 21 10 21 15 12 24 6 12 21 22 21 21 40 22 22 6 16 21 21 15 12 22 15 22 15 12 22 22 6 15 39 30 30 22 7 11 21 22 22 21 22 11 12 12 12 13 11 12 0 11 12 12 12 12 21 11 12 0 11 12 12 13 11 12 13 11 13 11 12 12 0 13 21 11 3 11 0',
 'German July car registrations up 14.2 pct yr / yr . 22 22 21 24 30 11 16 21 34 21 7 11 12 12 12 3 11 12 12 0 11 0',
 'FRANKFURT 1996-08-22 22 11 11 12',
 'German first-time registrations of motor vehicles jumped 14.2 percent in July this year from the year-earlier period , the Federal office for motor vehicles said on Thursday . 16 16 24 15 21 24 38 11 21 15 22 12 21 15 12 16 21 6 12 22 21 15 21 24 38 15 22 7 11 12 12 13 11 12 21 11 12 13 11 11 12 13 11 12 12 0 11 12 12 13 11 12 21 13 11 0',
 'The office said 356,725 new cars were registered in July 1996 -- 304,850 passenger cars and 15,613 trucks . 12 21 38 11 16 24 38 40 15 22 11 8 11 21 24 10 11 24 7 11 12 21 11 12 12 21 22 13 11 12 0 11 12 12 0 11 12 0',
 'The figures represent a 13.6 percent increase for passenger cars and a 2.2 percent decline for trucks from July 1995 . 12 24 41 12 11 21 21 15 21 24 10 12 11 21 21 15 24 15 22 11 7 11 12 21 11 12 12 12 13 11 12 0 11 12 12 12 13 11 13 11 12 0',
 'Motor-bike registration rose 32.7 percent in the period . 16 21 38 11 21 15 12 21 7 11 12 21 11 12 13 11 12 0',
 'The growth was partly due to an increased number of Germans buying German cars abroad , while manufacturers said that domestic demand was weak , the federal office said . 12 21 38 30 16 35 12 40 21 15 23 39 16 24 30 6 15 24 38 12 16 21 38 16 6 12 16 21 38 7 11 12 21 22 22 22 11 12 12 13 11 21 11 12 3 0 17 11 21 11 12 12 21 1 0 11 12 12 21 0',
 'Almost all German car manufacturers posted gains in registration numbers in the period . 30 12 16 21 24 38 24 15 21 24 15 12 21 7 11 12 12 12 12 21 11 13 11 12 13 11 12 0',
 'Volkswagen AG won 77,719 registrations , slightly more than a quarter of the total . 22 22 38 11 24 6 30 31 15 12 21 15 12 21 7 11 12 21 11 12 0 11 12 12 12 12 13 11 12 0',
 'Opel AG together with General Motors came in second place with 49,269 registrations , 16.4 percent of the overall figure . 22 22 30 15 22 23 38 15 16 21 15 11 24 6 11 21 15 12 16 21 7 11 12 3 13 11 12 21 13 11 12 13 11 12 0 11 12 13 11 12 12 0',
 'Third was Ford with 35,563 registrations , or 11.7 percent . 16 38 22 15 11 24 6 10 11 21 7 11 21 11 13 11 12 0 0 11 12 0',
 "Only Seat and Porsche had fewer registrations in July 1996 compared to last year 's July . 30 22 10 22 38 17 24 15 22 11 40 35 16 21 27 22 7 11 12 12 12 21 11 12 13 11 12 13 13 11 12 11 12 0",
 'Seat posted 3,420 registrations compared with 5522 registrations in July a year earlier . 21 38 11 24 40 15 11 24 15 22 12 21 31 7 11 21 11 12 13 13 11 12 13 11 11 12 3 0',
 "Porsche 's registrations fell to 554 from 643 . 22 27 24 38 35 11 15 11 7 11 11 12 21 13 11 13 11 0",
 'GREEK SOCIALISTS GIVE GREEN LIGHT TO PM FOR ELECTIONS . 16 24 41 22 22 35 22 15 24 7 11 12 21 11 12 13 11 13 11 0',
 'ATHENS 1996-08-22 24 11 11 12',
 "The Greek socialist party 's executive bureau gave the green light to Prime Minister Costas Simitis to call snap elections , its general secretary Costas Skandalidis told reporters . 12 22 16 21 27 16 21 38 12 16 21 35 22 22 42 23 35 37 37 24 6 29 16 21 22 22 38 24 7 11 12 12 12 11 12 12 21 11 12 12 13 11 12 21 11 21 22 22 11 0 11 12 12 11 12 21 11 0",
 'Prime Minister Costas Simitis is going to make an official announcement after a cabinet meeting later on Thursday , said Skandalidis . 22 22 42 22 42 39 35 37 12 16 21 15 12 21 21 30 15 22 6 38 22 7 11 12 21 11 21 22 22 22 11 12 12 13 11 12 12 3 13 11 0 21 11 0',
 '-- Dimitris Kontogiannis , Athens Newsroom +301 3311812-4 8 22 22 6 22 22 22 11 0 11 12 0 11 12 12 12',
 'BayerVB sets C$ 100 million six-year bond . 21 42 3 11 11 16 21 7 11 21 11 12 12 12 12 0',
 'LONDON 1996-08-22 22 11 11 12',
 'The following bond was announced by lead manager Toronto Dominion . 12 39 21 38 40 15 21 21 22 22 7 11 12 12 21 22 13 11 12 12 12 0',
 'BORROWER BAYERISCHE VEREINSBANK 22 22 22 11 12 12',
 'AMT C$ 100 MLN COUPON 6.625 MATURITY 24.SEP.02 22 3 11 22 21 11 22 11 0 11 12 12 12 12 12 11',
 'TYPE STRAIGHT ISS PRICE 100.92 PAY DATE 24.SEP.96 22 22 22 22 11 21 22 11 11 12 12 12 12 12 12 12',
 'FULL FEES 1.875 REOFFER 99.32 SPREAD +20 BP 22 24 11 22 11 22 11 22 11 12 11 12 12 12 12 12',
 'MOODY AA1 LISTING LUX PAY FREQ = 22 22 22 22 21 24 34 11 11 12 12 12 12 21',
 'S&P = DENOMS ( K ) 1-10-100 SALE LIMITS US / UK / CA 22 34 22 4 22 5 11 22 42 22 34 22 34 40 11 21 11 0 11 0 11 12 21 11 0 11 0 1',
 'NEG PLG NO CRS DEFLT NO FORCE MAJ = 22 22 12 22 22 12 41 20 34 11 12 12 12 12 12 21 22 22',
 'GOV LAW GERMAN HOME CTRY = TAX PROVS STANDARD 22 22 22 22 22 34 21 24 38 11 12 12 12 12 21 11 12 21',
 'MGT / UND 0.275 SELL CONC 1.60 PRAECIP = 22 34 22 11 37 22 11 22 34 11 0 11 12 21 11 12 12 21',
 'UNDERLYING GOVT BOND 7.0 PCT SEPT 2001 39 16 21 11 22 22 11 21 11 12 12 12 12 12',
 'NOTES BAYERISCHE VEREINSBANK IS JOINT LEAD MANAGER 24 41 22 42 42 22 21 11 21 11 21 22 11 12',
 '-- London Newsroom +44 171 542 7658 8 22 22 11 11 11 11 11 12 12 12 12 12 12',
 'Venantius sets $ 300 million January 1999 FRN . 16 24 3 11 11 22 11 22 7 11 12 11 12 12 12 12 12 0',
 'LONDON 1996-08-22 22 11 11 12',
 'The following floating-rate issue was announced by lead manager Lehman Brothers International . 12 39 21 21 38 40 15 21 21 22 23 22 7 11 12 12 12 21 22 13 11 12 12 12 12 0',
 'BORROWER VENANTIUS AB ( SWEDISH NATIONAL MORTGAGE AGENCY ) 22 22 22 4 22 22 22 21 5 11 12 12 0 11 12 12 12 0',
 'AMT $ 300 MLN SPREAD - 12.5 BP MATURITY 21.JAN.99 22 3 11 22 22 8 11 22 22 11 0 11 12 12 12 0 11 12 12 12',
 'TYPE FRN BASE 3M LIBOR PAY DATE S23.SEP.96 22 22 22 22 22 21 22 22 11 12 12 12 12 12 12 12',
 'LAST MOODY AA3 ISS PRICE 99.956 FULL FEES 10 BP 24 22 22 22 22 11 22 24 11 22 11 12 11 12 12 12 12 12 11 12',
 'LAST S&P AA+ REOFFER = 22 22 22 21 34 11 12 12 12 21',
 'NOTES S SHORT FIRST COUPON 24 22 22 22 22 11 12 12 12 12',
 'LISTING LONDON DENOMS ( K ) 1-10-100 SALE LIMITS US / UK / JP / FR 39 22 22 4 22 5 11 22 42 22 34 22 34 22 34 40 21 11 12 0 11 0 11 12 21 11 0 11 0 11 0 1',
 'NEG PLG YES CRS DEFLT NO FORCE MAJ IPMA 2 22 22 22 22 22 12 41 20 22 11 11 12 12 12 12 12 21 22 11 12',
 'GOV LAW ENGLISH HOME CTRY SWEDEN TAX PROVS STANDARD 22 22 22 22 22 22 21 24 38 11 12 12 12 12 12 12 12 21',
 'MGT / UND 5 BP SELL CONC 5 BP PRAECIP = 22 34 22 11 22 37 22 11 22 22 34 11 0 11 12 12 21 11 12 12 12 21',
 'NOTES ISSUED OFF EMTN PROGRAMME 24 38 21 22 22 11 21 11 12 12',
 '-- London Newsroom +44 171 542 8863 8 22 22 11 11 11 11 11 12 12 12 12 12 12',
 'Port conditions update - Syria - Lloyds Shipping . 21 24 41 8 22 8 22 22 7 11 12 21 0 11 0 11 12 0',
 'Port conditions from Lloyds Shipping Intelligence Service -- 21 24 15 22 22 22 22 8 11 12 13 11 12 12 12 0',
 'LATTAKIA , Aug 10 - waiting time at Lattakia and Tartous presently 24 hours . 22 6 22 11 8 39 21 15 22 10 22 30 11 24 7 11 0 11 12 12 21 11 13 11 12 12 3 11 12 0',
 'Israel plays down fears of war with Syria . 22 42 33 24 15 21 15 22 7 11 21 15 11 13 11 13 11 0',
 'Colleen Siegel 22 22 11 12',
 'JERUSALEM 1996-08-22 40 11 11 12',
 "Israel 's outgoing peace negotiator with Syria said on Thursday current tensions between the two countries appeared to be a storm in a teacup . 22 27 16 21 21 15 22 38 15 22 16 24 15 12 11 24 38 35 37 12 21 15 12 21 7 11 11 12 12 12 13 11 21 13 11 12 12 13 11 12 12 21 22 22 11 12 13 11 12 0",
 "Itamar Rabinovich , who as Israel 's ambassador to Washington conducted unfruitful negotiations with Syria , told Israel Radio it looked like Damascus wanted to talk rather than fight . 22 22 6 44 15 22 27 21 35 22 38 16 24 15 22 6 38 22 22 28 38 15 22 38 35 37 30 15 21 7 11 12 0 11 13 11 11 12 13 11 21 11 12 13 11 0 21 11 12 11 21 13 11 21 22 22 5 6 11 0",
 '" It appears to me the Syrian priority is still to negotiate . 0 28 42 35 28 12 16 21 42 30 35 37 7 0 11 21 13 11 11 12 12 21 3 21 22 0',
 'The Syrians are confused , they are definitely tense , but the general assessment here in Washington is that this is essentially a storm in a teacup , " he said . 12 23 41 40 6 28 41 30 16 6 10 12 16 21 30 15 22 42 15 12 42 30 12 21 15 12 21 6 0 28 38 7 11 12 21 1 0 11 21 22 11 0 0 11 12 12 3 13 11 21 17 11 21 3 11 12 13 11 12 0 0 11 21 0',
 'Rabinovich is winding up his term as ambassador . 21 42 39 33 29 21 15 21 7 11 21 22 15 11 12 13 11 0',
 'He will be replaced by Eliahu Ben-Elissar , a former Israeli envoy to Egypt and right-wing Likud party politician . 28 20 37 40 15 22 22 6 12 16 16 21 35 22 10 16 22 21 21 7 11 21 22 22 13 11 12 0 11 12 12 12 13 11 0 11 12 12 12 0',